name: Android CI

on: [push,pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Android Compilation Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3.3.0
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'gradle'
    - name: Copy secure values
      run: echo $GOOGLE_SERVICES > ./app/google-services.json
      env:
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
    - name: Make Gradle executable
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Move APK file to main folder
      run: mv ./app/build/outputs/apk/debug/app-debug.apk ./SingBuses-debug.apk
    - uses: actions/upload-artifact@v3
      with:
        name: SingBuses-debug-apk
        path: ./SingBuses-debug.apk
  device-test-latest:
    runs-on: macos-latest
    if: github.event_name != 'pull_request' && github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/tags/') && github.actor != 'dependabot[bot]'
    name: Test run on latest supported Android Device
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
      - name: Copy secure values
        run: echo $GOOGLE_SERVICES > ./app/google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      - name: Make Gradle executable
        run: chmod +x gradlew
      - name: List Available Android Devices
        run: $ANDROID_HOME/tools/bin/avdmanager list
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: 32
          target: google_apis
          profile: 'pixel_xl'
          arch: x86_64
          script: ./gradlew connectedAndroidTest
  device-test-full:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    name: Test run on all Android Devices
    strategy:
      fail-fast: true
      matrix:
        api-level: [21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 33]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3.3.0
    - name: Copy secure values
      run: echo $GOOGLE_SERVICES > ./app/google-services.json
      env:
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
    - name: Make Gradle executable
      run: chmod +x gradlew
    - name: List Available Android Devices
      run: $ANDROID_HOME/tools/bin/avdmanager list
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'gradle'
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2.27.0
      with:
        api-level: ${{ matrix.api-level }}
        target: google_apis
        profile: 'pixel_xl'
        arch: x86_64
        script: ./gradlew connectedAndroidTest
  release:
    name: Release APK file
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          token: ${{ secrets.GH_PAT }}
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'
      - name: Copy secure values
        run: echo $GOOGLE_SERVICES > ./app/google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      - name: Make Gradle executable
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Move APK file to main folder
        run: mv ./app/build/outputs/apk/debug/app-debug.apk ./SingBuses-debug.apk
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by GH Actions
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changes }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: SingBuses-debug.apk
      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
