name: Android CI

on: [push,pull_request]

jobs:
  build:
    name: Android Compilation Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Checkout all submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Copy secure values
      run: echo $GOOGLE_SERVICES > ./app/google-services.json
      env:
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
    - name: Make Gradle executable
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  device-test:
    runs-on: macOS-latest
    name: Android Device Test Runner
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Checkout all submodules
      run: git submodule update --init --recursive
    - name: Copy secure values
      run: echo $GOOGLE_SERVICES > ./app/google-services.json
      env:
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
    - name: Make Gradle executable
      run: chmod +x gradlew
    - name: List Available Android Devices
      run: $ANDROID_HOME/tools/bin/avdmanager list
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v1
      with:
        api-level: 28
        target: google_apis
        profile: 'pixel_xl'
        arch: x86_64
        script: ./gradlew connectedAndroidTest
  release:
    name: Release APK file
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Checkout all submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Copy secure values
      run: echo $GOOGLE_SERVICES > ./app/google-services.json
      env:
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
    - name: Make Gradle executable
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Move APK file to main folder
      run: mv ./app/build/outputs/apk/debug/app-debug.apk ./SingBuses-debug-gha.apk
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: SingBuses-debug-gha.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
